# Generated by Django 5.0.4 on 2024-04-09 15:39

import builtins
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='действие')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('start_date', models.DateField(default=datetime.date(2024, 4, 9), verbose_name='дата начала')),
                ('start_time', models.TimeField(default=datetime.time(15, 39, 15, 961705), verbose_name='время')),
                ('duration', models.DurationField(default='00:00:00', verbose_name='выполнять чч:мм:сс')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('in 2 days', 'Раз в 2 дня'), ('in 3 days', 'Раз в 3 дня'), ('in 4 days', 'Раз в 4 дня'), ('in 5 days', 'Раз в 5 дней'), ('in 6 days', 'Раз в 6 дней')], default='daily', verbose_name='периодичность')),
                ('is_nice', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('award', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_habit', to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': (builtins.id,),
            },
        ),
    ]
