# Generated by Django 5.0.4 on 2024-04-09 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 18, 6, 915021), verbose_name='время'),
        ),
    ]
